version: "3.8"

services:
  # 前端服務 (React) - 開發模式
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src:cached
      - ./client/public:/app/public:cached
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - server
    container_name: fullstack_client_dev
    stdin_open: true
    tty: true

  # 後端服務 (Node.js) - 開發模式
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/appdb
      - JWT_SECRET=your-jwt-secret-key
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres
    container_name: fullstack_server_dev
    command: npx nodemon server.js

  # PostgreSQL 資料庫
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: fullstack_postgres_dev

volumes:
  postgres_dev_data:

networks:
  default:
    name: fullstack_dev_network